import os
os.system ('termux-setup-storage')
os.system ('clear')
os.system ('figlet Fx9 hacker')
print ('')
print ('')
print ("{1} Hk IP facebook ")
print ('')
print ('{2} Hack wifi')
print ('')
print ('\033[1;32mFor Example, Choose a Number \033[1;31m1,2,3,4,5...')
v7x2 = input (" \033[1;33mFx9\033[1;31m==> ")
if v7x2 == '1' :
        os.system ('clear')
        print ('')
        print ("Loading..........!")
        os.system ('figlet Hk facebook') 
fx9 = input (" \033[1;33mIP ==> ")
if fx9 == '100069307100747' :
        os.system ('cmatrix')
        print ("") 
        print ('ereer')
elif v7x2 == '2' :
        os.system ('clear')
        print ("Loading..........!")
        t(0.1,'\n\t   \033[1;31m[   PLEASE WAIT .... ]')
        timeout(1)
        print ('Done...')
        os.system ('clear')
        os.system ('git clone https://github.com/sabri-zaki/EasY_HaCk')
        os.system ('mv EasY_HaCk ~')
        restart ()        
